### ISSUE TITLE
We need to get the river name that is closest to a point feature in Geocontext

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/geocontext#88]
# Problem

We would like to associate a site with the name of the river closest to it.

# Solution
Not all rivers have names from the database.

We are going to create a PostgreSQL function and then from geocontext we call that function to get the name of the river

I have added a PostgreSQL function to do this
```
CREATE OR REPLACE  FUNCTION   finder (latitude double precision, longitude double precision) RETURNS character varying
    LANGUAGE plpgsql
    AS $$
  DECLARE 
	river_name character varying;
  BEGIN
    SELECT entity_name  INTO river_name
	FROM hydr_lines_exp
	WHERE entity_name is not null
	ORDER BY wkb_geometry <-> st_transform((st_setsrid(st_makepoint(latitude,longitude),4326)),3857)
	LIMIT 1;
	RETURN river_name;
	

  END
$$;
```

Then from the database client, we just call `select finder(24.23,-29.79)`

![return](https://user-images.githubusercontent.com/2510900/54338909-ea558a00-463b-11e9-8f5e-bc7625d9e292.png)

cc @dimasciput

**Comment by timlinux** [comment]
How will this be defined and managed in terms of our conceptual framework of 

* collection
* group
* service

I would prefer that it be treated in a way that end users could add / remove it from groups etc rather than us hard coding this into the geocontext platform and then having the river name magically appearing in some groups. Can you elaborate on how an end user will interact with this in the admin panel?

**Comment by andretheronsa** [comment]
@timlinux @NyakudyaA 
We can consider adding a "Function" to the framework?
The user could then do some basic functions between a point and a service as in.
Point: X Y
Function : CLOSEST
Service: Rivers

This feature should also be documented in the readme as it is not obvious that the river database env needs to be specified.
